from django.urls import path

urlpatterns = [
    
        
    #urls of AdminHOD
    #  path('admin_home/', ),
    # path('add_staff/', ),
    # path('add_staff_save/', ),
    # path('manage_staff/', ),
    # path('edit_staff/<staff_id>/', ),
    # path('edit_staff_save/', ),
    # path('delete_staff/<staff_id>/', ),
    # path('add_course/', ),
    # path('add_course_save/', ),
    # path('manage_course/', ),
    # path('edit_course/<course_id>/', ),
    # path('edit_course_save/', ),
    # path('delete_course/<course_id>/', ),
    # path('manage_session/', ),
    # path('add_session/', ),
    # path('add_session_save/', ),
    # path('edit_session/<session_id>', ),
    # path('edit_session_save/', ),
    # path('delete_session/<session_id>/', ),
    # path('add_student/', ),
    # path('add_student_save/', ),
    # path('edit_student/<student_id>', ),
    # path('edit_student_save/', ),
    # path('manage_student/', ),
    # path('delete_student/<student_id>/', ),
    # path('add_subject/', ),
    # path('add_subject_save/', ),
    # path('manage_subject/', ),
    # path('edit_subject/<subject_id>/', ),
    # path('edit_subject_save/', ),
    # path('delete_subject/<subject_id>/', ),
    # path('check_email_exist/', ),
    # path('check_username_exist/', ),
    # path('admin_view_library/'),
    # path('admin_update_library/'),
    # path('admin_delete_library/'),
    # path('student_leave_view/', ),
    # path('student_leave_approve/<leave_id>/', ),
    # path('student_leave_reject/<leave_id>/', ),
    # path('staff_leave_view/', ),
    # path('staff_leave_approve/<leave_id>/', ),
    # path('staff_leave_reject/<leave_id>/', ),
    # path('admin_view_attendance/', ),
    # path('admin_get_attendance_dates/', ),
    # path('admin_get_attendance_student/', ),
    # path('admin_profile/', ),
    # path('admin_profile_update/', ),
]
