# Generated by Django 5.1.4 on 2025-01-17 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 13, 35, 14, 324434)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 13, 35, 14, 324434)),
        ),
    ]
