# Generated by Django 5.1.4 on 2025-01-18 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 18, 14, 32, 43, 138229)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 18, 14, 32, 43, 138229)),
        ),
    ]
