# Generated by Django 5.1.4 on 2025-01-21 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 9, 37, 16, 378616)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 9, 37, 16, 378616)),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/6596/6596121.png', upload_to='student_img/'),
        ),
    ]
