# Generated by Django 5.1.4 on 2025-01-21 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 9, 40, 37, 734525)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 9, 40, 37, 734525)),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(default='student_img/avatar.jpg', upload_to='student_img/'),
        ),
    ]
