# Generated by Django 5.1.4 on 2025-01-25 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstudent',
            old_name='leave_mesasge',
            new_name='leave_message',
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 25, 23, 6, 58, 977624)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 25, 23, 6, 58, 972734)),
        ),
    ]
