# Generated by Django 5.1.4 on 2025-01-26 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_rename_leave_mesasge_leavereportstudent_leave_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 19, 11, 51, 21370)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 19, 11, 51, 21370)),
        ),
    ]
