# Generated by Django 5.1.5 on 2025-02-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_leavereportstudent_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 22, 28, 39, 582297)),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_start_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 22, 28, 39, 582297)),
        ),
    ]
