# Generated by Django 5.1.4 on 2025-01-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='class_id',
        ),
    ]
