# Generated by Django 5.1.4 on 2025-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('staff', 'Staff'), ('student', 'Student'), ('both', 'Both')], default='both', max_length=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
