# Generated by Django 5.1.4 on 2025-01-17 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_alter_homeworksubmission_submssion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 13, 35, 14, 342648)),
        ),
    ]
