# Generated by Django 5.1.4 on 2025-01-24 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0012_remove_homeworksubmission_submssion_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 16, 59, 45, 777367)),
        ),
    ]
