# Generated by Django 5.1.4 on 2025-01-24 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0018_remove_homework_title_homework_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 21, 18, 32, 322627)),
        ),
    ]
