# Generated by Django 5.1.4 on 2025-01-25 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0020_alter_homework_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 16, 20, 41, 963771)),
        ),
    ]
