# Generated by Django 5.1.4 on 2025-01-25 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0022_alter_homeworksubmission_submssion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 23, 6, 58, 999371)),
        ),
    ]
