# Generated by Django 5.1.4 on 2025-01-26 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0023_alter_homeworksubmission_submssion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 19, 11, 51, 44457)),
        ),
    ]
