# Generated by Django 5.1.4 on 2025-01-30 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0024_alter_homeworksubmission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 15, 5, 18, 619372)),
        ),
    ]
