# Generated by Django 5.1.5 on 2025-02-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0033_alter_homework_description_and_more'),
        ('subjects', '0003_remove_subjects_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
        ),
    ]
