# Generated by Django 5.1.5 on 2025-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0034_alter_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
