# Generated by Django 5.1.5 on 2025-02-17 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0036_alter_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=datetime.date(2025, 2, 17)),
        ),
    ]
