# Generated by Django 5.1.5 on 2025-02-17 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0037_alter_homeworksubmission_submssion_date'),
        ('staff', '0012_alter_leavereportstaff_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffs'),
        ),
    ]
