# Generated by Django 5.1.5 on 2025-02-17 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0038_homework_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submssion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
