# Generated by Django 5.1.5 on 2025-02-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0039_alter_homeworksubmission_submssion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworksubmission',
            old_name='submssion_date',
            new_name='submission_date',
        ),
    ]
