# Generated by Django 5.1.5 on 2025-02-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0029_alter_attendancereport_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 22, 28, 39, 588400)),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='attendence_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 22, 28, 39, 588400)),
        ),
    ]
