# Generated by Django 5.1.5 on 2025-02-06 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0030_alter_attendancereport_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 6, 15, 52, 37, 318937, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='attendence_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 6, 15, 52, 37, 318306, tzinfo=datetime.timezone.utc)),
        ),
    ]
