# Generated by Django 5.1.4 on 2025-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_img'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='result_img/'),
        ),
    ]
