# Generated by Django 5.1.5 on 2025-02-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_image_alter_examresult_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='student_id',
            new_name='student',
        ),
    ]
