# Generated by Django 5.1.4 on 2025-01-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('staff', '0002_delete_adminhod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='admin',
            new_name='name',
        ),
        migrations.AddField(
            model_name='staffs',
            name='class_teacher',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel'),
            preserve_default=False,
        ),
    ]
