# Generated by Django 5.1.4 on 2025-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('staff', '0003_rename_admin_staffs_name_staffs_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='teaches_classes',
            field=models.ManyToManyField(related_name='teachers', to='classes.classmodel'),
        ),
    ]
