# Generated by Django 5.1.4 on 2025-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffs_teaches_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_img/'),
        ),
    ]
