# Generated by Django 5.1.4 on 2025-01-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffs_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
