# Generated by Django 5.1.4 on 2025-01-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_profile_picture_staffs_image'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='subject_teaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
        ),
    ]
