# Generated by Django 5.1.4 on 2025-01-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staffs_subject_teaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='subject_teaches',
        ),
    ]
