# Generated by Django 5.1.4 on 2025-01-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_staffs_subject_teaches'),
        ('subjects', '0003_remove_subjects_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='subject_teaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
        ),
    ]
