# Generated by Django 5.1.5 on 2025-02-06 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staffs_subject_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_end_date',
            field=models.DateTimeField(default=datetime.date(2025, 2, 6)),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_start_date',
            field=models.DateTimeField(default=datetime.date(2025, 2, 6)),
        ),
    ]
