# Generated by Django 5.1.5 on 2025-02-18 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_leavereportstaff_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
