# Generated by Django 5.1.4 on 2025-01-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classmodel_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='subjects',
        ),
    ]
